### ISSUE TITLE
Allow to create Healer with a custom query

### ISSUE THREAD

**Issue by ntk148v** [vCloud-DFTBA/faythe#51]
By now, Healer only accepts a default query: `up{job=~\".*compute-cadvisor.*|.*compute-node.*\"} < 1`. We should allow user to pass their query, a `job` name might be different.

**Comment by vtdat** [comment]
This feature is supported in https://github.com/vCloud-DFTBA/faythe/pull/30/files#diff-350dfc1a15a2d6c6c0bea41046436b08R59. If no query is defined, use default query.

However, if we use different query, the logic should be changed respectively. Because, `up{job=~\".*compute-cadvisor.*|.*compute-node.*\"} < 1` returns 2 metrics for one host then we evaluate based on both. It varies from case to case.

**Comment by ntk148v** [comment]
Implemented.
